markdown: kramdown
highlighter: pygments
permalink: /posts/:title
future: false
kramdown:
  gfm: true

name: Matt Yoho
url: http://mattyoho.com
description: Wholesale optimism distributor.
twitter: mattyoho
github: mattyoho
instagram: mattyoho
gravatar_url: http://www.gravatar.com/avatar/52ee95ca6e345d86a414741dccaa6dce
email: contact@mattyoho.com
email_base64: Y29udGFjdEBtYXR0eW9oby5jb20=
